# Generated by Django 3.1.5 on 2022-04-30 23:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('recently_used', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coloring.author')),
            ],
        ),
        migrations.CreateModel(
            name='Sighting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(default='default.jpg', null=True, upload_to='images')),
                ('name', models.CharField(max_length=50, null=True)),
                ('species', models.TextField(null=True)),
                ('date', models.DateField(default=datetime.date(2022, 4, 30))),
                ('time', models.TimeField(default='23:53:17')),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('notes', models.TextField(null=True)),
                ('first_edit', models.IntegerField(default=1)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coloring.author')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sighting', to='coloring.trip')),
            ],
        ),
    ]
