# Generated by Django 3.1.5 on 2022-04-26 20:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coloring', '0002_trip_sighting'),
    ]

    operations = [
        migrations.AddField(
            model_name='sighting',
            name='dummy',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
