# Generated by Django 3.1.5 on 2022-05-01 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coloring', '0002_auto_20220501_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coloring.author'),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='time',
            field=models.TimeField(default='02:21:15'),
        ),
    ]
