# Generated by Django 3.1.5 on 2022-04-26 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coloring', '0003_sighting_dummy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sighting',
            name='dummy',
        ),
    ]
