# Generated by Django 3.1.5 on 2022-04-27 16:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coloring', '0004_remove_sighting_dummy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sighting',
            old_name='desc',
            new_name='notes',
        ),
        migrations.RemoveField(
            model_name='sighting',
            name='date_time',
        ),
        migrations.AddField(
            model_name='sighting',
            name='date',
            field=models.DateField(default=datetime.date(2022, 4, 27)),
        ),
        migrations.AddField(
            model_name='sighting',
            name='time',
            field=models.TimeField(default='16:37:20'),
        ),
    ]
