# Generated by Django 3.1.5 on 2022-05-01 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coloring', '0004_auto_20220501_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='image',
            field=models.ImageField(default='default.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='time',
            field=models.TimeField(default='23:50:24'),
        ),
    ]
