# Generated by Django 3.1.5 on 2022-04-27 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coloring', '0005_auto_20220427_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='time',
            field=models.TimeField(default='20:51:36'),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sighting', to='coloring.trip'),
        ),
    ]
