# Generated by Django 3.1.5 on 2022-05-02 03:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coloring', '0005_auto_20220501_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='date',
            field=models.DateField(default=datetime.date(2022, 5, 2)),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='image',
            field=models.ImageField(default='/images/default.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='time',
            field=models.TimeField(default='03:43:38'),
        ),
    ]
