# Generated by Django 3.1.5 on 2022-04-28 16:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coloring', '0006_auto_20220427_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='date',
            field=models.DateField(default=datetime.date(2022, 4, 28)),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='time',
            field=models.TimeField(default='16:46:57'),
        ),
    ]
