# Generated by Django 3.1.5 on 2022-04-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coloring', '0008_auto_20220428_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='time',
            field=models.TimeField(default='16:57:51'),
        ),
    ]
