# Generated by Django 3.1.5 on 2022-04-28 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coloring', '0011_auto_20220428_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='time',
            field=models.TimeField(default='17:02:50'),
        ),
    ]
