# Generated by Django 3.1.5 on 2022-04-29 02:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coloring', '0012_auto_20220428_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='sighting',
            name='first_edit',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='date',
            field=models.DateField(default=datetime.date(2022, 4, 29)),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='time',
            field=models.TimeField(default='02:26:02'),
        ),
    ]
