# Generated by Django 3.1.5 on 2022-04-29 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coloring', '0014_auto_20220429_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='first_edit',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='time',
            field=models.TimeField(default='02:43:13'),
        ),
    ]
